management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info,metrics
      cors:
        allowed-origins: "http://localhost:5173"
        allowed-methods: GET

server:
  port: 8089

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ecom_db
    username: root
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
